//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoFrontend_V3.ServicioUsuarios {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserPublic", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserPublic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ApellidoUsuario {
            get {
                return this.ApellidoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoUsuarioField, value) != true)) {
                    this.ApellidoUsuarioField = value;
                    this.RaisePropertyChanged("ApellidoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resp_Simple", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Resp_Simple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resp_Login", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Resp_Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private proyectoFrontend_V3.ServicioUsuarios.User UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public proyectoFrontend_V3.ServicioUsuarios.User Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int ID_RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        private int ID_EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Usuario {
            get {
                return this.ID_UsuarioField;
            }
            set {
                if ((this.ID_UsuarioField.Equals(value) != true)) {
                    this.ID_UsuarioField = value;
                    this.RaisePropertyChanged("ID_Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreUsuario {
            get {
                return this.NombreUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreUsuarioField, value) != true)) {
                    this.NombreUsuarioField = value;
                    this.RaisePropertyChanged("NombreUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApellidoUsuario {
            get {
                return this.ApellidoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoUsuarioField, value) != true)) {
                    this.ApellidoUsuarioField = value;
                    this.RaisePropertyChanged("ApellidoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Alias {
            get {
                return this.AliasField;
            }
            set {
                if ((object.ReferenceEquals(this.AliasField, value) != true)) {
                    this.AliasField = value;
                    this.RaisePropertyChanged("Alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ID_Rol {
            get {
                return this.ID_RolField;
            }
            set {
                if ((this.ID_RolField.Equals(value) != true)) {
                    this.ID_RolField = value;
                    this.RaisePropertyChanged("ID_Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ID_Estado {
            get {
                return this.ID_EstadoField;
            }
            set {
                if ((this.ID_EstadoField.Equals(value) != true)) {
                    this.ID_EstadoField = value;
                    this.RaisePropertyChanged("ID_Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaRegistroField, value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Resp_Users", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Resp_Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private proyectoFrontend_V3.ServicioUsuarios.User[] UsuariosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public proyectoFrontend_V3.ServicioUsuarios.User[] Usuarios {
            get {
                return this.UsuariosField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuariosField, value) != true)) {
                    this.UsuariosField = value;
                    this.RaisePropertyChanged("Usuarios");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Categoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_CategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Categoria {
            get {
                return this.ID_CategoriaField;
            }
            set {
                if ((this.ID_CategoriaField.Equals(value) != true)) {
                    this.ID_CategoriaField = value;
                    this.RaisePropertyChanged("ID_Categoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreCategoria {
            get {
                return this.NombreCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCategoriaField, value) != true)) {
                    this.NombreCategoriaField = value;
                    this.RaisePropertyChanged("NombreCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Autor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ID_AutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoAutorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NacionalidadField;
        
        private System.DateTime FechaNacimientoField;
        
        private System.Nullable<System.DateTime> FechaDefuncionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID_Autor {
            get {
                return this.ID_AutorField;
            }
            set {
                if ((this.ID_AutorField.Equals(value) != true)) {
                    this.ID_AutorField = value;
                    this.RaisePropertyChanged("ID_Autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreAutor {
            get {
                return this.NombreAutorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAutorField, value) != true)) {
                    this.NombreAutorField = value;
                    this.RaisePropertyChanged("NombreAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ApellidoAutor {
            get {
                return this.ApellidoAutorField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoAutorField, value) != true)) {
                    this.ApellidoAutorField = value;
                    this.RaisePropertyChanged("ApellidoAutor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nacionalidad {
            get {
                return this.NacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.NacionalidadField, value) != true)) {
                    this.NacionalidadField = value;
                    this.RaisePropertyChanged("Nacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<System.DateTime> FechaDefuncion {
            get {
                return this.FechaDefuncionField;
            }
            set {
                if ((this.FechaDefuncionField.Equals(value) != true)) {
                    this.FechaDefuncionField = value;
                    this.RaisePropertyChanged("FechaDefuncion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioUsuarios.WS_UsersSoap")]
    public interface WS_UsersSoap {
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarPublico", ReplyAction="*")]
        proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponse RegistrarPublico(proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarPublico", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponse> RegistrarPublicoAsync(proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest request);
        
        // CODEGEN: Generating message contract since element name login from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciarSesion", ReplyAction="*")]
        proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponse IniciarSesion(proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IniciarSesion", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponse> IniciarSesionAsync(proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest request);
        
        // CODEGEN: Generating message contract since element name request from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarAdmin", ReplyAction="*")]
        proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponse RegistrarAdmin(proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegistrarAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponse> RegistrarAdminAsync(proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest request);
        
        // CODEGEN: Generating message contract since element name ObtenerUsuariosResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuarios", ReplyAction="*")]
        proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponse ObtenerUsuarios(proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUsuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponse> ObtenerUsuariosAsync(proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest request);
        
        // CODEGEN: Generating message contract since element name categoria from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCategoria", ReplyAction="*")]
        proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponse CrearCategoria(proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponse> CrearCategoriaAsync(proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest request);
        
        // CODEGEN: Generating message contract since element name autor from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearAutor", ReplyAction="*")]
        proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponse CrearAutor(proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearAutor", ReplyAction="*")]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponse> CrearAutorAsync(proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarPublicoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarPublico", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequestBody Body;
        
        public RegistrarPublicoRequest() {
        }
        
        public RegistrarPublicoRequest(proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarPublicoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.UserPublic request;
        
        public RegistrarPublicoRequestBody() {
        }
        
        public RegistrarPublicoRequestBody(proyectoFrontend_V3.ServicioUsuarios.UserPublic request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarPublicoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarPublicoResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponseBody Body;
        
        public RegistrarPublicoResponse() {
        }
        
        public RegistrarPublicoResponse(proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarPublicoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple RegistrarPublicoResult;
        
        public RegistrarPublicoResponseBody() {
        }
        
        public RegistrarPublicoResponseBody(proyectoFrontend_V3.ServicioUsuarios.Resp_Simple RegistrarPublicoResult) {
            this.RegistrarPublicoResult = RegistrarPublicoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesion", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequestBody Body;
        
        public IniciarSesionRequest() {
        }
        
        public IniciarSesionRequest(proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IniciarSesionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clave;
        
        public IniciarSesionRequestBody() {
        }
        
        public IniciarSesionRequestBody(string login, string clave) {
            this.login = login;
            this.clave = clave;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IniciarSesionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IniciarSesionResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponseBody Body;
        
        public IniciarSesionResponse() {
        }
        
        public IniciarSesionResponse(proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IniciarSesionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Login IniciarSesionResult;
        
        public IniciarSesionResponseBody() {
        }
        
        public IniciarSesionResponseBody(proyectoFrontend_V3.ServicioUsuarios.Resp_Login IniciarSesionResult) {
            this.IniciarSesionResult = IniciarSesionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarAdmin", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequestBody Body;
        
        public RegistrarAdminRequest() {
        }
        
        public RegistrarAdminRequest(proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.User request;
        
        public RegistrarAdminRequestBody() {
        }
        
        public RegistrarAdminRequestBody(proyectoFrontend_V3.ServicioUsuarios.User request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistrarAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistrarAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponseBody Body;
        
        public RegistrarAdminResponse() {
        }
        
        public RegistrarAdminResponse(proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegistrarAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple RegistrarAdminResult;
        
        public RegistrarAdminResponseBody() {
        }
        
        public RegistrarAdminResponseBody(proyectoFrontend_V3.ServicioUsuarios.Resp_Simple RegistrarAdminResult) {
            this.RegistrarAdminResult = RegistrarAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuarios", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequestBody Body;
        
        public ObtenerUsuariosRequest() {
        }
        
        public ObtenerUsuariosRequest(proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ObtenerUsuariosRequestBody {
        
        public ObtenerUsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerUsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerUsuariosResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponseBody Body;
        
        public ObtenerUsuariosResponse() {
        }
        
        public ObtenerUsuariosResponse(proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerUsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Users ObtenerUsuariosResult;
        
        public ObtenerUsuariosResponseBody() {
        }
        
        public ObtenerUsuariosResponseBody(proyectoFrontend_V3.ServicioUsuarios.Resp_Users ObtenerUsuariosResult) {
            this.ObtenerUsuariosResult = ObtenerUsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearCategoria", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequestBody Body;
        
        public CrearCategoriaRequest() {
        }
        
        public CrearCategoriaRequest(proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Categoria categoria;
        
        public CrearCategoriaRequestBody() {
        }
        
        public CrearCategoriaRequestBody(proyectoFrontend_V3.ServicioUsuarios.Categoria categoria) {
            this.categoria = categoria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponseBody Body;
        
        public CrearCategoriaResponse() {
        }
        
        public CrearCategoriaResponse(proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple CrearCategoriaResult;
        
        public CrearCategoriaResponseBody() {
        }
        
        public CrearCategoriaResponseBody(proyectoFrontend_V3.ServicioUsuarios.Resp_Simple CrearCategoriaResult) {
            this.CrearCategoriaResult = CrearCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearAutorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearAutor", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequestBody Body;
        
        public CrearAutorRequest() {
        }
        
        public CrearAutorRequest(proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearAutorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Autor autor;
        
        public CrearAutorRequestBody() {
        }
        
        public CrearAutorRequestBody(proyectoFrontend_V3.ServicioUsuarios.Autor autor) {
            this.autor = autor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearAutorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearAutorResponse", Namespace="http://tempuri.org/", Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponseBody Body;
        
        public CrearAutorResponse() {
        }
        
        public CrearAutorResponse(proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearAutorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple CrearAutorResult;
        
        public CrearAutorResponseBody() {
        }
        
        public CrearAutorResponseBody(proyectoFrontend_V3.ServicioUsuarios.Resp_Simple CrearAutorResult) {
            this.CrearAutorResult = CrearAutorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_UsersSoapChannel : proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_UsersSoapClient : System.ServiceModel.ClientBase<proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap>, proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap {
        
        public WS_UsersSoapClient() {
        }
        
        public WS_UsersSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_UsersSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_UsersSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_UsersSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponse proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.RegistrarPublico(proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest request) {
            return base.Channel.RegistrarPublico(request);
        }
        
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple RegistrarPublico(proyectoFrontend_V3.ServicioUsuarios.UserPublic request) {
            proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequestBody();
            inValue.Body.request = request;
            proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponse retVal = ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).RegistrarPublico(inValue);
            return retVal.Body.RegistrarPublicoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponse> proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.RegistrarPublicoAsync(proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest request) {
            return base.Channel.RegistrarPublicoAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoResponse> RegistrarPublicoAsync(proyectoFrontend_V3.ServicioUsuarios.UserPublic request) {
            proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.RegistrarPublicoRequestBody();
            inValue.Body.request = request;
            return ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).RegistrarPublicoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponse proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.IniciarSesion(proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest request) {
            return base.Channel.IniciarSesion(request);
        }
        
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Login IniciarSesion(string login, string clave) {
            proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequestBody();
            inValue.Body.login = login;
            inValue.Body.clave = clave;
            proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponse retVal = ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).IniciarSesion(inValue);
            return retVal.Body.IniciarSesionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponse> proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.IniciarSesionAsync(proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest request) {
            return base.Channel.IniciarSesionAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.IniciarSesionResponse> IniciarSesionAsync(string login, string clave) {
            proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.IniciarSesionRequestBody();
            inValue.Body.login = login;
            inValue.Body.clave = clave;
            return ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).IniciarSesionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponse proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.RegistrarAdmin(proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest request) {
            return base.Channel.RegistrarAdmin(request);
        }
        
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple RegistrarAdmin(proyectoFrontend_V3.ServicioUsuarios.User request) {
            proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequestBody();
            inValue.Body.request = request;
            proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponse retVal = ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).RegistrarAdmin(inValue);
            return retVal.Body.RegistrarAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponse> proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.RegistrarAdminAsync(proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest request) {
            return base.Channel.RegistrarAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminResponse> RegistrarAdminAsync(proyectoFrontend_V3.ServicioUsuarios.User request) {
            proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.RegistrarAdminRequestBody();
            inValue.Body.request = request;
            return ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).RegistrarAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponse proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.ObtenerUsuarios(proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest request) {
            return base.Channel.ObtenerUsuarios(request);
        }
        
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Users ObtenerUsuarios() {
            proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequestBody();
            proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponse retVal = ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).ObtenerUsuarios(inValue);
            return retVal.Body.ObtenerUsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponse> proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.ObtenerUsuariosAsync(proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest request) {
            return base.Channel.ObtenerUsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosResponse> ObtenerUsuariosAsync() {
            proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.ObtenerUsuariosRequestBody();
            return ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).ObtenerUsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponse proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.CrearCategoria(proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest request) {
            return base.Channel.CrearCategoria(request);
        }
        
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple CrearCategoria(proyectoFrontend_V3.ServicioUsuarios.Categoria categoria) {
            proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequestBody();
            inValue.Body.categoria = categoria;
            proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponse retVal = ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).CrearCategoria(inValue);
            return retVal.Body.CrearCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponse> proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.CrearCategoriaAsync(proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest request) {
            return base.Channel.CrearCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaResponse> CrearCategoriaAsync(proyectoFrontend_V3.ServicioUsuarios.Categoria categoria) {
            proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.CrearCategoriaRequestBody();
            inValue.Body.categoria = categoria;
            return ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).CrearCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponse proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.CrearAutor(proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest request) {
            return base.Channel.CrearAutor(request);
        }
        
        public proyectoFrontend_V3.ServicioUsuarios.Resp_Simple CrearAutor(proyectoFrontend_V3.ServicioUsuarios.Autor autor) {
            proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequestBody();
            inValue.Body.autor = autor;
            proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponse retVal = ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).CrearAutor(inValue);
            return retVal.Body.CrearAutorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponse> proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap.CrearAutorAsync(proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest request) {
            return base.Channel.CrearAutorAsync(request);
        }
        
        public System.Threading.Tasks.Task<proyectoFrontend_V3.ServicioUsuarios.CrearAutorResponse> CrearAutorAsync(proyectoFrontend_V3.ServicioUsuarios.Autor autor) {
            proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest inValue = new proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequest();
            inValue.Body = new proyectoFrontend_V3.ServicioUsuarios.CrearAutorRequestBody();
            inValue.Body.autor = autor;
            return ((proyectoFrontend_V3.ServicioUsuarios.WS_UsersSoap)(this)).CrearAutorAsync(inValue);
        }
    }
}
